### PR TITLE
Use golang.org/x/sys/unix to work around syscall differences

### LINKED ISSUE #15: Errors at FreeBSD
At FreeBSD, it get the next errors:

```
../pkg/mod/github.com/muesli/termenv@v0.6.0/termenv_unix.go:30:12: undefined: termStatusReport
../pkg/mod/github.com/muesli/termenv@v0.6.0/termenv_unix.go:52:12: undefined: termStatusReport
../pkg/mod/github.com/muesli/termenv@v0.6.0/termenv_unix.go:76:9: readfds.Bits undefined (type syscall.FdSet has no field or method Bits)
../pkg/mod/github.com/muesli/termenv@v0.6.0/termenv_unix.go:87:12: readfds.Bits undefined (type syscall.FdSet has no field or method Bits)
```

### PR DESCRIPTION
**Pull request by twpayne**
This should fix #15. @tredoe could you verify?

This also removes the assumption that the platform uses 64-bit words, which was previously encoded in the assumption that `syscall.FdSet.Bits` consisted of `int64`s.

### CODE REVIEW

**Comment by twpayne** [comment]
[This message on gophers.slack.com](https://gophers.slack.com/archives/C029RQSEE/p1596847867348200) is also relevant.

**Comment by twpayne** [comment]
Sorry, this isn't quite ready for review yet. There's another problem.

The current code uses a mix of `_GOOS.go` filename suffixes (which only get built on `runtime.GOOS`) and build flags, which mean that the `termStatusReport` function is still missing on some platforms. I'll only be able to untangle this tomorrow evening at the earliest.

**Comment by twpayne** [comment]
This is now ready for review.

**Comment by tredoe** [comment]
I've tested on FreeBSD 12.1 and I got:
```
$ go test -v .
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/sys v0.0.0-20200116001909-b77594299b42
# github.com/muesli/termenv [github.com/muesli/termenv.test]
./termenv_unix.go:31:12: undefined: termStatusReport
./termenv_unix.go:53:12: undefined: termStatusReport
./termenv_unix.go:77:9: readfds.Bits undefined (type syscall.FdSet has no field or method Bits)
./termenv_unix.go:96:12: readfds.Bits undefined (type syscall.FdSet has no field or method Bits)
FAIL	github.com/muesli/termenv [build failed]
```

**Comment by tredoe** [comment]
I get the error
```
$ go test -v .
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/sys v0.0.0-20200116001909-b77594299b42
# github.com/muesli/termenv [github.com/muesli/termenv.test]
./termenv_unix.go:31:12: undefined: termStatusReport
./termenv_unix.go:53:12: undefined: termStatusReport
./termenv_unix.go:77:9: readfds.Bits undefined (type syscall.FdSet has no field or method Bits)
./termenv_unix.go:96:12: readfds.Bits undefined (type syscall.FdSet has no field or method Bits)
FAIL	github.com/muesli/termenv [build failed]
```

**Comment by tredoe** [comment]
Note: I cloned it using `git clone https://github.com/muesli/termenv.git

**Comment by twpayne** [comment]
@tredoe, you need to test the `freebsd` branch, not `master`.

**Comment by tredoe** [comment]
```
git clone https://github.com/twpayne/termenv.git

[tre@freebsd ~/termenv]$ go test -v .
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/sys v0.0.0-20200116001909-b77594299b42
# github.com/muesli/termenv [github.com/muesli/termenv.test]
./termenv_unix.go:31:12: undefined: termStatusReport
./termenv_unix.go:53:12: undefined: termStatusReport
./termenv_unix.go:77:9: readfds.Bits undefined (type syscall.FdSet has no field or method Bits)
./termenv_unix.go:96:12: readfds.Bits undefined (type syscall.FdSet has no field or method Bits)
FAIL	github.com/muesli/termenv [build failed]
```

**Comment by twpayne** [comment]
The commands you entered checked out my `master` branch, not the `freebsd` branch. Run the following:

```sh
$ git fetch origin pull/16/head:freebsd
$ git checkout freebsd
$ go test ./...
```

**Comment by tredoe** [comment]
It works now. Thanks!

```
$ git checkout freebsd

$ go test -v .
go: downloading golang.org/x/sys v0.0.0-20200116001909-b77594299b42
go: downloading github.com/mattn/go-isatty v0.0.12
=== RUN   TestStyleWidth
--- PASS: TestStyleWidth (0.00s)
=== RUN   TestTermEnv
--- PASS: TestTermEnv (0.00s)
=== RUN   TestRendering
--- PASS: TestRendering (0.00s)
=== RUN   TestColorConversion
--- PASS: TestColorConversion (0.00s)
=== RUN   TestAscii
--- PASS: TestAscii (0.00s)
=== RUN   TestANSIProfile
--- PASS: TestANSIProfile (0.00s)
=== RUN   TestANSI256Profile
--- PASS: TestANSI256Profile (0.00s)
=== RUN   TestTrueColorProfile
--- PASS: TestTrueColorProfile (0.00s)
=== RUN   TestStyles
--- PASS: TestStyles (0.00s)
=== RUN   TestTemplateHelpers
--- PASS: TestTemplateHelpers (0.00s)
PASS
ok  	github.com/muesli/termenv	0.003s
```

**Comment by muesli** [comment]
@twpayne Looking great as usual :+1: 

Will give this a spin on macOS and Linux and probably merge this later tonight.

**Comment by twpayne** [comment]
Thank you very much for merging this. Would you mind tagging a new version?

**Comment by muesli** [comment]
@twpayne No, thank you for the PR! :smile:

New release up in a minute!

**Pull request merged**
