### PR TITLE
Enable colors on default linux tty

### LINKED ISSUE #37: Colors on default linux tty
Currently, when I use termenv in default linux tty (TERM=linux), ColorProfile() returns Ascii, so there are no colors in output. But it does support standard ANSI color palette. 

I've made a PR to fix that, if that's OK with you.

### PR DESCRIPTION
**Pull request by vasa-chi**
Closes #37

### CODE REVIEW

**Comment by muesli** [comment]
Is it actually a safe assumption, that the default tty always supports ANSI on Linux?

**Comment by vasa-chi** [comment]
Well, I've checked several current distributions, and default tty has `TERM=linux` and has basic color support. Honestly don't know how to verify it more thoroughly :)

**Comment by vasa-chi** [comment]
I think it is also possible to run `tput colors` to get colors support at runtime (on linux and macOS at least). I feel that if OS thinks, that tty has support for 8 colors, then it is OK to do the same.

**Comment by muesli** [comment]
@vasa-chi Sorry this took so long, but I finally found the time to properly review this. I planned to rebase and integrate your little change, but realized I couldn't push to your fork's master branch. I've manually integrated this change here now. Thanks for your contribution!

**Comment by vasa-chi** [comment]
Thank you :)

**Pull request closed without merging**
