### PR TITLE
termenv: add shim for js

### PR DESCRIPTION
**Pull request by paralin**
Supports GOOS=js GOARCH=wasm go build

### CODE REVIEW

**Comment by muesli** [comment]
That seems reasonable. Thank you!

**Comment by makeworld-the-better-one** [comment]
Why would the foreground color not default to ANSI color 15, which is white? I guess it doesn't matter much overall, but gray seems like a strange default. Is there some history there I'm unaware of?

**Comment by muesli** [comment]
@makeworld-the-better-one Historically speaking it has always(?) been ANSI 7, at least on Linux, DOS, Windows, *BSD.

**Comment by paralin** [comment]
Fwiw the xterm background defaults to dark gray.

**Pull request merged**
